INSERT INTO weather_info (
    weather_info_id,
    Temperature,
    Humidity,
    Pressure,
    Rain_Status,
    Rain_Intensity,
    Gas_Level,
    D_index,
    E_Alert,
    D_Alert,
    R_Prediction
  )
VALUES (
    weather_info_id:intINSERT INTO weather_info (
        weather_info_id,
        Temperature,
        Humidity,
        Pressure,
        Rain_Status,
        Rain_Intensity,
        Gas_Level,
        D_index,
        E_Alert,
        D_Alert,
        R_Prediction
      )
    VALUES (
        weather_info_id:int,
        'Temperature:varchar',
        'Humidity:varchar',
        'Pressure:varchar',
        'Rain_Status:varchar',
        'Rain_Intensity:float',
        'Gas_Level:varchar',
        'D_index:float',
        'E_Alert:text',
        'D_Alert:text',
        'R_Prediction:varchar'
      );,
    'Temperature:varchar',
    'Humidity:varchar',
    'Pressure:varchar',
    'Rain_Status:varchar',
    'Rain_Intensity:float',
    'Gas_Level:varchar',
    'D_index:float',
    'E_Alert:text',
    'D_Alert:text',
    'R_Prediction:varchar'
  );